{'id': 40386, 'article': 'GDB1044', 'brand': {'id': 3, 'name': 'TRW'},
 'name': 'Колодки передние AUDI 80 (B4), CHERY AMULET, VW GOLF III, PASSAT (3A) GDB1044', 'offers': [
    {'warehouse': {'id': 27820, 'name': 'BERG MSK', 'type': 1}, 'price': 3822, 'average_period': 0, 'assured_period': 0,
     'reliability': 100, 'is_transit': False, 'quantity': 2, 'available_more': False, 'multiplication_factor': 1,
     'delivery_type': 1},
    {'warehouse': {'id': 30914297, 'name': 'GTR', 'type': 3}, 'price': 3898.44, 'average_period': 2,
     'assured_period': 2, 'reliability': 82, 'is_transit': False, 'quantity': 3, 'available_more': False,
     'multiplication_factor': 1, 'delivery_type': 1},
    {'warehouse': {'id': 64853952, 'name': 'PCF', 'type': 3}, 'price': 3898.44, 'average_period': 2,
     'assured_period': 2, 'reliability': 85, 'is_transit': False, 'quantity': 1, 'available_more': False,
     'multiplication_factor': 1, 'delivery_type': 1},
    {'warehouse': {'id': 115541616, 'name': 'LFR', 'type': 3}, 'price': 3898.44, 'average_period': 4,
     'assured_period': 4, 'reliability': 74, 'is_transit': False, 'quantity': 3, 'available_more': False,
     'multiplication_factor': 1, 'delivery_type': 1},
    {'warehouse': {'id': 11005789, 'name': 'ESK', 'type': 3}, 'price': 3898.44, 'average_period': 6,
     'assured_period': 6, 'reliability': 75, 'is_transit': False, 'quantity': 3, 'available_more': False,
     'multiplication_factor': 1, 'delivery_type': 1},
    {'warehouse': {'id': 336, 'name': 'DMT', 'type': 3}, 'price': 4322.68, 'average_period': 1, 'assured_period': 1,
     'reliability': 92, 'is_transit': False, 'quantity': 1, 'available_more': False, 'multiplication_factor': 1,
     'delivery_type': 1},
    {'warehouse': {'id': 141965367, 'name': 'RCI', 'type': 3}, 'price': 4322.7, 'average_period': 2,
     'assured_period': 2, 'reliability': 85, 'is_transit': False, 'quantity': 3, 'available_more': False,
     'multiplication_factor': 1, 'delivery_type': 1},
    {'warehouse': {'id': 141965415, 'name': 'STD', 'type': 3}, 'price': 4323.15, 'average_period': 4,
     'assured_period': 4, 'reliability': 78, 'is_transit': False, 'quantity': 1, 'available_more': False,
     'multiplication_factor': 1, 'delivery_type': 1},
    {'warehouse': {'id': 36576345, 'name': 'MUZ', 'type': 3}, 'price': 4366, 'average_period': 1, 'assured_period': 1,
     'reliability': 94, 'is_transit': False, 'quantity': 1, 'available_more': False, 'multiplication_factor': 1,
     'delivery_type': 1},
    {'warehouse': {'id': 10949, 'name': 'FCS', 'type': 3}, 'price': 4385.17, 'average_period': 1, 'assured_period': 1,
     'reliability': 96, 'is_transit': False, 'quantity': 2, 'available_more': False, 'multiplication_factor': 1,
     'delivery_type': 1},
    {'warehouse': {'id': 73541553, 'name': 'DIB', 'type': 3}, 'price': 4557.24, 'average_period': 1,
     'assured_period': 1, 'reliability': 82, 'is_transit': False, 'quantity': 4, 'available_more': False,
     'multiplication_factor': 1, 'delivery_type': 1},
    {'warehouse': {'id': 29617743, 'name': 'ACW', 'type': 3}, 'price': 4671.88, 'average_period': 5,
     'assured_period': 5, 'reliability': 75, 'is_transit': False, 'quantity': 4, 'available_more': False,
     'multiplication_factor': 1, 'delivery_type': 1},
    {'warehouse': {'id': 102322800, 'name': 'DUB', 'type': 3}, 'price': 4796.57, 'average_period': 6,
     'assured_period': 6, 'reliability': 46, 'is_transit': False, 'quantity': 3, 'available_more': False,
     'multiplication_factor': 1, 'delivery_type': 1},
    {'warehouse': {'id': 124081293, 'name': 'EVD', 'type': 3}, 'price': 4849.84, 'average_period': 14,
     'assured_period': 14, 'reliability': 75, 'is_transit': False, 'quantity': 3, 'available_more': False,
     'multiplication_factor': 1, 'delivery_type': 1},
    {'warehouse': {'id': 94203483, 'name': 'ААА', 'type': 3}, 'price': 5006.94, 'average_period': 2,
     'assured_period': 2, 'reliability': 75, 'is_transit': False, 'quantity': 2, 'available_more': False,
     'multiplication_factor': 1, 'delivery_type': 1},
    {'warehouse': {'id': 5085317, 'name': 'GGP', 'type': 3}, 'price': 5014.31, 'average_period': 6, 'assured_period': 6,
     'reliability': 80, 'is_transit': False, 'quantity': 4, 'available_more': False, 'multiplication_factor': 1,
     'delivery_type': 1},
    {'warehouse': {'id': 134777232, 'name': 'RTS', 'type': 3}, 'price': 5036.34, 'average_period': 5,
     'assured_period': 5, 'reliability': 93, 'is_transit': False, 'quantity': 1, 'available_more': False,
     'multiplication_factor': 1, 'delivery_type': 1},
    {'warehouse': {'id': 136510677, 'name': 'GHK', 'type': 3}, 'price': 5121.74, 'average_period': 5,
     'assured_period': 5, 'reliability': 71, 'is_transit': False, 'quantity': 1, 'available_more': False,
     'multiplication_factor': 1, 'delivery_type': 1},
    {'warehouse': {'id': 70208745, 'name': 'PGD', 'type': 3}, 'price': 5132.53, 'average_period': 7,
     'assured_period': 7, 'reliability': 67, 'is_transit': False, 'quantity': 1, 'available_more': False,
     'multiplication_factor': 1, 'delivery_type': 1},
    {'warehouse': {'id': 179875638, 'name': 'RSB', 'type': 3}, 'price': 5172.25, 'average_period': 2,
     'assured_period': 2, 'reliability': 95, 'is_transit': False, 'quantity': 3, 'available_more': False,
     'multiplication_factor': 1, 'delivery_type': 1},
    {'warehouse': {'id': 134779485, 'name': 'RTZ', 'type': 3}, 'price': 5205.99, 'average_period': 2,
     'assured_period': 2, 'reliability': 88, 'is_transit': False, 'quantity': 1, 'available_more': False,
     'multiplication_factor': 1, 'delivery_type': 1},
    {'warehouse': {'id': 1150450, 'name': 'PDA', 'type': 3}, 'price': 5247.24, 'average_period': 1, 'assured_period': 1,
     'reliability': 87, 'is_transit': False, 'quantity': 2, 'available_more': False, 'multiplication_factor': 1,
     'delivery_type': 1},
    {'warehouse': {'id': 28258467, 'name': 'SRY', 'type': 3}, 'price': 5247.24, 'average_period': 4,
     'assured_period': 4, 'reliability': 88, 'is_transit': False, 'quantity': 1, 'available_more': False,
     'multiplication_factor': 1, 'delivery_type': 1},
    {'warehouse': {'id': 147075813, 'name': 'MGR', 'type': 3}, 'price': 5829.58, 'average_period': 5,
     'assured_period': 5, 'reliability': 58, 'is_transit': False, 'quantity': 1, 'available_more': False,
     'multiplication_factor': 1, 'delivery_type': 1},
    {'warehouse': {'id': 101394225, 'name': 'ACC', 'type': 3}, 'price': 5980.03, 'average_period': 6,
     'assured_period': 6, 'reliability': 93, 'is_transit': False, 'quantity': 1, 'available_more': False,
     'multiplication_factor': 1, 'delivery_type': 1},
    {'warehouse': {'id': 48773241, 'name': 'OEI', 'type': 3}, 'price': 6891.68, 'average_period': 30,
     'assured_period': 30, 'reliability': 73, 'is_transit': False, 'quantity': 14, 'available_more': False,
     'multiplication_factor': 1, 'delivery_type': 1},
    {'warehouse': {'id': 23755611, 'name': 'Эмираты-3', 'type': 3}, 'price': 7241.4, 'average_period': 30,
     'assured_period': 30, 'reliability': 75, 'is_transit': False, 'quantity': 11, 'available_more': False,
     'multiplication_factor': 1, 'delivery_type': 1},
    {'warehouse': {'id': 73899576, 'name': 'FJH', 'type': 3}, 'price': 8846.64, 'average_period': 44,
     'assured_period': 44, 'reliability': 89, 'is_transit': False, 'quantity': 3, 'available_more': False,
     'multiplication_factor': 1, 'delivery_type': 1}], 'source_idx': '0'}
